DROP TABLE RESERVA_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE TIPO_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE RESERVA CASCADE CONSTRAINTS;
DROP TABLE HABITACION CASCADE CONSTRAINTS;
DROP TABLE TIPO_HABITACION CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CIUDAD;
DROP SEQUENCE SEQ_CLIENTE;
DROP SEQUENCE SEQ_HOTEL;
DROP SEQUENCE SEQ_TIPO_HAB;
DROP SEQUENCE SEQ_HAB;
DROP SEQUENCE SEQ_SERV;
DROP SEQUENCE SEQ_RES;
DROP SEQUENCE SEQ_RS;

CREATE TABLE CIUDAD (
  ID_CIUDAD NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  PAIS VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);

CREATE TABLE CLIENTE (
  ID_CLIENTE NUMBER(10) NOT NULL,
  IDENTIFICACION VARCHAR2(20) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  APELLIDOS VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(200) NOT NULL,
  TELEFONO VARCHAR2(20),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
  CONSTRAINT UQ_CLIE_IDEN UNIQUE (IDENTIFICACION),
  CONSTRAINT UQ_CLIE_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE HOTEL (
  ID_HOTEL NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  DIRECCION VARCHAR2(100),
  TELEFONO VARCHAR2(50),
  DESCRIPCION VARCHAR2(500),
  ID_CIUDAD NUMBER(10) NOT NULL,
  CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL),
  CONSTRAINT FK_HOTEL_CIUDAD FOREIGN KEY (ID_CIUDAD)
    REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE TIPO_HABITACION (
  ID_TIPO NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  COSTO_BAJA NUMBER(10,2) NOT NULL,
  COSTO_ALTA NUMBER(10,2) NOT NULL,
  DIMENSIONES NUMBER(5,2),
  VISTA VARCHAR2(100),
  CAPACIDAD NUMBER(3) NOT NULL,
  ID_HOTEL NUMBER(10) NOT NULL,
  CONSTRAINT PK_TIPO_HAB PRIMARY KEY (ID_TIPO),
  CONSTRAINT FK_TIPO_HOTEL FOREIGN KEY (ID_HOTEL)
    REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT CK_TH_COSTO1 CHECK (COSTO_BAJA >= 0),
  CONSTRAINT CK_TH_COSTO2 CHECK (COSTO_ALTA >= 0),
  CONSTRAINT CK_TH_CAP CHECK (CAPACIDAD > 0),
  CONSTRAINT UQ_TH_HOTEL_NOM UNIQUE (ID_HOTEL, NOMBRE)
);

CREATE TABLE HABITACION (
  ID_HABITACION NUMBER(10) NOT NULL,
  NUMERO VARCHAR2(10) NOT NULL,
  PISO NUMBER(3),
  DISPONIBLE VARCHAR2(2) DEFAULT 'SI' NOT NULL,
  ID_HOTEL NUMBER(10) NOT NULL,
  ID_TIPO NUMBER(10) NOT NULL,
  CONSTRAINT PK_HAB PRIMARY KEY (ID_HABITACION),
  CONSTRAINT FK_HAB_HOTEL FOREIGN KEY (ID_HOTEL)
    REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT FK_HAB_TIPO FOREIGN KEY (ID_TIPO)
    REFERENCES TIPO_HABITACION(ID_TIPO),
  CONSTRAINT CK_HAB_DISP CHECK (DISPONIBLE IN ('SI','NO')),
  CONSTRAINT UQ_HAB_HOTEL_NUM UNIQUE (ID_HOTEL, NUMERO)
);

CREATE TABLE SERVICIO (
  ID_SERVICIO NUMBER(10) NOT NULL,
  NOMBRE VARCHAR2(100) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  TIPO_COSTO VARCHAR2(20) NOT NULL,
  PRECIO NUMBER(10,2) NOT NULL,
  APLICA VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_SERV PRIMARY KEY (ID_SERVICIO),
  CONSTRAINT UQ_SERV_NOM UNIQUE (NOMBRE),
  CONSTRAINT CK_SERV_TIPO CHECK (TIPO_COSTO IN ('FIJO','CONSUMO')),
  CONSTRAINT CK_SERV_APL CHECK (APLICA IN ('RESERVA','NOCHE','PERSONA')),
  CONSTRAINT CK_SERV_PRECIO CHECK (PRECIO >= 0)
);

CREATE TABLE TIPO_SERVICIO (
  ID_TIPO NUMBER(10) NOT NULL,
  ID_SERVICIO NUMBER(10) NOT NULL,
  PRECIO_ESPECIAL NUMBER(10,2) NOT NULL,
  CONSTRAINT PK_TS PRIMARY KEY (ID_TIPO, ID_SERVICIO),
  CONSTRAINT FK_TS_TIPO FOREIGN KEY (ID_TIPO)
    REFERENCES TIPO_HABITACION(ID_TIPO),
  CONSTRAINT FK_TS_SERV FOREIGN KEY (ID_SERVICIO)
    REFERENCES SERVICIO(ID_SERVICIO),
  CONSTRAINT CK_TS_PRECIO CHECK (PRECIO_ESPECIAL >= 0)
);

CREATE TABLE RESERVA (
  ID_RESERVA NUMBER(10) NOT NULL,
  FECHA_ENTRADA DATE NOT NULL,
  FECHA_SALIDA DATE NOT NULL,
  FECHA_RESERVA DATE NOT NULL,
  NUM_ADULTOS NUMBER(3) NOT NULL,
  NUM_MENORES NUMBER(3) NOT NULL,
  PRECIO_TOTAL NUMBER(10,2) NOT NULL,
  ESTADO VARCHAR2(20) NOT NULL,
  ID_CLIENTE NUMBER(10) NOT NULL,
  ID_TIPO NUMBER(10) NOT NULL,
  ID_HOTEL NUMBER(10) NOT NULL,
  CONSTRAINT PK_RES PRIMARY KEY (ID_RESERVA),
  CONSTRAINT FK_RES_CLI FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_RES_TIPO FOREIGN KEY (ID_TIPO)
    REFERENCES TIPO_HABITACION(ID_TIPO),
  CONSTRAINT FK_RES_HOT FOREIGN KEY (ID_HOTEL)
    REFERENCES HOTEL(ID_HOTEL),
  CONSTRAINT CK_RES_FECHAS CHECK (FECHA_SALIDA > FECHA_ENTRADA),
  CONSTRAINT CK_RES_ADULTOS CHECK (NUM_ADULTOS >= 1),
  CONSTRAINT CK_RES_MENORES CHECK (NUM_MENORES >= 0),
  CONSTRAINT CK_RES_PRECIO CHECK (PRECIO_TOTAL >= 0),
  CONSTRAINT CK_RES_ESTADO CHECK (ESTADO IN ('ACTIVA','CANCELADA','FINALIZADA'))
);

CREATE TABLE RESERVA_SERVICIO (
  ID_RESERVA_SERVICIO NUMBER(10) NOT NULL,
  ID_RESERVA NUMBER(10) NOT NULL,
  ID_SERVICIO NUMBER(10) NOT NULL,
  CANTIDAD NUMBER(3),
  PRECIO_APLICADO NUMBER(10,2) NOT NULL,
  CONSTRAINT PK_RS PRIMARY KEY (ID_RESERVA_SERVICIO),
  CONSTRAINT FK_RS_RES FOREIGN KEY (ID_RESERVA)
    REFERENCES RESERVA(ID_RESERVA),
  CONSTRAINT FK_RS_SERV FOREIGN KEY (ID_SERVICIO)
    REFERENCES SERVICIO(ID_SERVICIO),
  CONSTRAINT CK_RS_CANT CHECK (CANTIDAD IS NULL OR CANTIDAD > 0),
  CONSTRAINT CK_RS_PRECIO CHECK (PRECIO_APLICADO >= 0)
);



CREATE SEQUENCE SEQ_CIUDAD START WITH 1;
CREATE SEQUENCE SEQ_CLIENTE START WITH 1;
CREATE SEQUENCE SEQ_HOTEL START WITH 1;
CREATE SEQUENCE SEQ_TIPO_HAB START WITH 1;
CREATE SEQUENCE SEQ_HAB START WITH 1;
CREATE SEQUENCE SEQ_SERV START WITH 1;
CREATE SEQUENCE SEQ_RES START WITH 1;
CREATE SEQUENCE SEQ_RS START WITH 1;




-- CIUDADES
INSERT INTO CIUDAD VALUES (SEQ_CIUDAD.NEXTVAL, 'Bogotá', 'Colombia');
INSERT INTO CIUDAD VALUES (SEQ_CIUDAD.NEXTVAL, 'Medellín', 'Colombia');

-- HOTELES
INSERT INTO HOTEL VALUES (SEQ_HOTEL.NEXTVAL, 'Dann Norte', 'Calle 100', '3001111111', 'Hotel en Bogotá', 1);
INSERT INTO HOTEL VALUES (SEQ_HOTEL.NEXTVAL, 'Dann Centro', 'Carrera 7', '3002222222', 'Hotel en Bogotá', 1);
INSERT INTO HOTEL VALUES (SEQ_HOTEL.NEXTVAL, 'Dann Poblado', 'El Poblado', '3003333333', 'Hotel en Medellín', 2);

-- CLIENTES
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL, '1001', 'Juan', 'Perez', 'juan1@mail.com', '310000001');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL, '1002', 'Maria', 'Lopez', 'maria2@mail.com', '310000002');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL, '1003', 'Carlos', 'Gomez', 'carlos3@mail.com', '310000003');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL, '1004', 'Laura', 'Torres', 'laura4@mail.com', '310000004');
INSERT INTO CLIENTE VALUES (SEQ_CLIENTE.NEXTVAL, '1005', 'Sofia', 'Ruiz', 'sofia5@mail.com', '310000005');

-- SERVICIOS
INSERT INTO SERVICIO VALUES (SEQ_SERV.NEXTVAL, 'Desayuno', 'Desayuno por persona', 'CONSUMO', 20000, 'PERSONA');
INSERT INTO SERVICIO VALUES (SEQ_SERV.NEXTVAL, 'Spa', 'Acceso al spa', 'FIJO', 50000, 'RESERVA');
INSERT INTO SERVICIO VALUES (SEQ_SERV.NEXTVAL, 'Airport shuttle', 'Transporte aeropuerto', 'FIJO', 40000, 'RESERVA');
INSERT INTO SERVICIO VALUES (SEQ_SERV.NEXTVAL, 'Valet Parking', 'Servicio de parqueo', 'FIJO', 30000, 'NOCHE');

-- TIPOS DE HABITACION
INSERT INTO TIPO_HABITACION VALUES (SEQ_TIPO_HAB.NEXTVAL, 'Suite Junior', 180000, 250000, 35, 'Ciudad', 2, 1);
INSERT INTO TIPO_HABITACION VALUES (SEQ_TIPO_HAB.NEXTVAL, 'Habitacion Doble', 120000, 170000, 25, 'Interior', 2, 1);
INSERT INTO TIPO_HABITACION VALUES (SEQ_TIPO_HAB.NEXTVAL, 'Suite Presidencial', 300000, 450000, 60, 'Ciudad', 4, 2);
INSERT INTO TIPO_HABITACION VALUES (SEQ_TIPO_HAB.NEXTVAL, 'Standard', 90000, 130000, 20, 'Interior', 2, 3);

-- HABITACIONES
INSERT INTO HABITACION VALUES (SEQ_HAB.NEXTVAL, '101', 1, 'SI', 1, 1);
INSERT INTO HABITACION VALUES (SEQ_HAB.NEXTVAL, '102', 1, 'SI', 1, 2);
INSERT INTO HABITACION VALUES (SEQ_HAB.NEXTVAL, '201', 2, 'SI', 2, 1);
INSERT INTO HABITACION VALUES (SEQ_HAB.NEXTVAL, '301', 3, 'SI', 3, 3);

-- TIPOS DE SERVICIO POR TIPO DE HABITACION
INSERT INTO TIPO_SERVICIO VALUES (1, 1, 15000);
INSERT INTO TIPO_SERVICIO VALUES (1, 2, 50000);
INSERT INTO TIPO_SERVICIO VALUES (2, 1, 15000);
INSERT INTO TIPO_SERVICIO VALUES (3, 3, 40000);
INSERT INTO TIPO_SERVICIO VALUES (4, 4, 25000);

-- RESERVAS
INSERT INTO RESERVA VALUES (
  SEQ_RES.NEXTVAL,
  DATE '2026-05-10',
  DATE '2026-05-13',
  DATE '2026-04-26',
  2,
  1,
  700000,
  'ACTIVA',
  1,
  1,
  1
);

INSERT INTO RESERVA VALUES (
  SEQ_RES.NEXTVAL,
  DATE '2026-05-15',
  DATE '2026-05-18',
  DATE '2026-04-26',
  1,
  0,
  510000,
  'ACTIVA',
  2,
  2,
  1
);

INSERT INTO RESERVA VALUES (
  SEQ_RES.NEXTVAL,
  DATE '2026-06-01',
  DATE '2026-06-04',
  DATE '2026-04-26',
  3,
  0,
  1350000,
  'ACTIVA',
  3,
  3,
  2
);

INSERT INTO RESERVA VALUES (
  SEQ_RES.NEXTVAL,
  DATE '2026-06-10',
  DATE '2026-06-12',
  DATE '2026-04-26',
  2,
  0,
  260000,
  'ACTIVA',
  4,
  4,
  3
);

-- RESERVA_SERVICIO
INSERT INTO RESERVA_SERVICIO VALUES (SEQ_RS.NEXTVAL, 1, 1, 2, 40000);
INSERT INTO RESERVA_SERVICIO VALUES (SEQ_RS.NEXTVAL, 1, 2, 1, 50000);
INSERT INTO RESERVA_SERVICIO VALUES (SEQ_RS.NEXTVAL, 2, 3, 1, 40000);
INSERT INTO RESERVA_SERVICIO VALUES (SEQ_RS.NEXTVAL, 3, 1, 3, 60000);
INSERT INTO RESERVA_SERVICIO VALUES (SEQ_RS.NEXTVAL, 4, 4, 2, 60000);


 --RFC1
SELECT h.ID_HABITACION,
       h.NUMERO,
       th.NOMBRE AS TIPO_HABITACION,
       th.CAPACIDAD,
       th.VISTA,
       th.COSTO_ALTA AS PRECIO_NOCHE
FROM HABITACION h
JOIN TIPO_HABITACION th
  ON h.ID_TIPO = th.ID_TIPO
 AND h.ID_HOTEL = th.ID_HOTEL
LEFT JOIN RESERVA r
  ON r.ID_HOTEL = h.ID_HOTEL
 AND r.ID_TIPO = h.ID_TIPO
 AND r.ESTADO = 'ACTIVA'
 AND r.FECHA_ENTRADA < DATE '2026-05-13'
 AND r.FECHA_SALIDA > DATE '2026-05-10'
WHERE h.ID_HOTEL = 1
  AND h.DISPONIBLE = 'SI'
  AND r.ID_RESERVA IS NULL
ORDER BY h.NUMERO;

--RFC2
SELECT r.FECHA_RESERVA,
       c.NOMBRE AS NOMBRE_CIUDAD,
       h.NOMBRE AS NOMBRE_HOTEL, 
       COUNT(*) AS TOTAL_RESERVAS
FROM RESERVA r
JOIN HOTEL h ON r.ID_HOTEL = h.ID_HOTEL
JOIN CIUDAD c ON h.ID_CIUDAD = c.ID_CIUDAD
WHERE r.FECHA_RESERVA BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
GROUP BY r.FECHA_RESERVA, c.NOMBRE, h.NOMBRE
ORDER BY r.FECHA_RESERVA, c.NOMBRE, h.NOMBRE;

--RFC3
SELECT r.FECHA_ENTRADA,
       c.NOMBRE AS CIUDAD,
       h.NOMBRE AS HOTEL,
       SUM(r.NUM_ADULTOS + r.NUM_MENORES) AS TOTAL_HUESPEDES
FROM RESERVA r
JOIN HOTEL h
  ON r.ID_HOTEL = h.ID_HOTEL
JOIN CIUDAD c
  ON h.ID_CIUDAD = c.ID_CIUDAD
WHERE r.FECHA_ENTRADA BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
GROUP BY r.FECHA_ENTRADA, c.NOMBRE, h.NOMBRE
ORDER BY r.FECHA_ENTRADA, c.NOMBRE, h.NOMBRE;

--RFC4
SELECT c.NOMBRE AS CIUDAD,
       h.NOMBRE AS HOTEL,
       SUM(r.PRECIO_TOTAL) AS INGRESO_TOTAL
FROM RESERVA r
JOIN HOTEL h
  ON r.ID_HOTEL = h.ID_HOTEL
JOIN CIUDAD c
  ON h.ID_CIUDAD = c.ID_CIUDAD
WHERE r.FECHA_RESERVA BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
  AND r.ESTADO = 'ACTIVA'
GROUP BY c.NOMBRE, h.NOMBRE
ORDER BY c.NOMBRE, h.NOMBRE;

--RFC5.1
SELECT c.NOMBRE AS CIUDAD,
       h.NOMBRE AS HOTEL,
       th.NOMBRE AS TIPO_HABITACION,
       COUNT(*) AS TOTAL_RESERVAS
FROM RESERVA r
JOIN HOTEL h
  ON r.ID_HOTEL = h.ID_HOTEL
JOIN CIUDAD c
  ON h.ID_CIUDAD = c.ID_CIUDAD
JOIN TIPO_HABITACION th
  ON r.ID_TIPO = th.ID_TIPO
WHERE r.FECHA_RESERVA BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
  AND r.ESTADO = 'ACTIVA'
GROUP BY c.NOMBRE, h.NOMBRE, th.NOMBRE
ORDER BY TOTAL_RESERVAS DESC;

--RFC5.2
SELECT c.NOMBRE AS CIUDAD,
       h.NOMBRE AS HOTEL,
       s.NOMBRE AS SERVICIO,
       COUNT(*) AS TOTAL_USOS
FROM RESERVA_SERVICIO rs
JOIN RESERVA r
  ON rs.ID_RESERVA = r.ID_RESERVA
JOIN HOTEL h
  ON r.ID_HOTEL = h.ID_HOTEL
JOIN CIUDAD c
  ON h.ID_CIUDAD = c.ID_CIUDAD
JOIN SERVICIO s
  ON rs.ID_SERVICIO = s.ID_SERVICIO
WHERE r.FECHA_RESERVA BETWEEN DATE '2026-01-01' AND DATE '2026-12-31'
  AND r.ESTADO = 'ACTIVA'
GROUP BY c.NOMBRE, h.NOMBRE, s.NOMBRE
ORDER BY TOTAL_USOS DESC;